### PR TITLE
Fix two filters resulting in empty object when removing the same row/columns

### LINKED ISSUE #236: Two sample filters with the same sample erase the object
I'll get an mrep written up, but basically with rna-seq data (probably happens in the others), if I apply an RNAfilt that remove sample A1, and then another RNAfilt that ALSO removes sample A1, the object gets blown up (resulting object has 0 samples).

Usually this doesn't happen in an R coding session because the user makes the second filter after applying the first, so the sample doesn't exist, but in the app they are all created at once, so two filters can be targeting the same samples for removal.

### PR DESCRIPTION
**Pull request by evanglass**
Fixes #236

### CODE REVIEW

File: R/applyFilt.R [hunk 1]
```diff
@@ -2024,55 +2024,125 @@ pmartR_filter_worker <- function (filter_object, omicsData) {
...
+      # Check if there is at least one sample name that will be removed
+      if (length(inds) > 0) {
+        
+        # Remove the rows in f_data that correspond to the samples that should
+        # be removed.
+        omicsData$f_data <- omicsData$f_data[-inds, ]
+        
+      }
 
+      valid_names <- names(omicsData$e_data)
```
Comment (clabornd) [inline R/applyFilt.R:2056]: leave out edata_cname here

File: R/applyFilt.R [hunk 2]
```diff
@@ -2081,10 +2151,23 @@ pmartR_filter_worker <- function (filter_object, omicsData) {
     # remove any emeta molecules from e_meta and e_data #
     if (!is.null(filter_object$e_meta_remove)) {
 
+      valid_names <- omicsData$e_meta[, which(names(omicsData$e_meta) == emeta_cname)]
+      
+      # Warn if trying to remove biomolecules which are no longer in the data
```
Comment (clabornd) [inline R/applyFilt.R:2156]: Should this be commented out?  Looks to be in the correct spot.

**Comment by clabornd** [comment]
The issue with the protein filter not throwing a warning is -i think- due to the fact that it determines which e_data to remove based on which e_meta identifiers to be removed are present in the data:

```
# Find rows in e_meta that correspond to proteins to be filtered.
protfilt.ids = which(omicsData$e_meta[,pro_id] %in% pro_filt)

# Extricate the indices for the peptides that will be filtered.
pep_filt <- as.character(setdiff(omicsData$e_meta[protfilt.ids, pep_id],
                                 omicsData$e_meta[-protfilt.ids, pep_id]))
```

Protein data is a bit different, in that it's e_meta_cname references different things than e_data_cname.  The e_meta values to be removed are no longer present, so it decides there's no e_data to remove and doesn't throw the warning for non-existent e_data.  Adding the warning block for e_meta you had commented out in pmart_filter_worker seemed to work for me - at least for throwing a warning for non-existent e_meta.

File: R/applyFilt.R (hunk 2 above)
Comment (evanglass) [reply R/applyFilt.R:2156]: It was just giving a lot of extra warnings when running the existing tests, so I commented it out.

File: R/applyFilt.R (hunk 1 above)
Comment (evanglass) [reply R/applyFilt.R:2056]: What do you mean by this?

Comment (evanglass) [reply R/applyFilt.R:2056]: Is this what you mean? 
```R
valid_names <- names(omicsData$e_data)
valid_names <- valid_names[valid_names != edata_cname]
```

Comment (clabornd) [reply R/applyFilt.R:2056]: If I'm reading this correctly `valid_names` will include the identifier column specified by `attr(object, "cnames")$edata_cname` (usually the first column), but only the names of the other columns are actual sample names to be potentially removed.  Probably doesn't matter, but I think this should be:

`valid_names <- names(omicsData$e_data[-which(names(omicsData$e_data) == edata_cname)])`

or

`valid_names <- omicsData$f_data[,get_fdata_cname(omicsData)]`

File: R/applyFilt.R (hunk 2 above)
Comment (clabornd) [reply R/applyFilt.R:2156]: Ah yea I see them too, since the filter worker filters out the e_data first *as well as any corresponding stuff in e_meta* and then it's all already gone once it gets to removing e_meta.  Hmmm...I'll think a bit about what to do here...

File: R/applyFilt.R (hunk 1 above)
Comment (evanglass) [reply R/applyFilt.R:2056]: Hmm... it seems like changing it is causing a lot more test failures

Comment (clabornd) [reply R/applyFilt.R:2056]: Yea I'm seeing these, looking into it

Comment (clabornd) [reply R/applyFilt.R:2056]: Sorry yea this borks the indexing.  I think it's fine actually, just weird because the first element of valid_names isn't actually a valid name, but is needed for the right indexing.

**Comment by clabornd** [comment]
@evanglass I pushed a change to trigger the warnings also on missing e_meta.  Could you give a quick sniff test when you have a minute?

**Comment by evanglass** [comment]
It passes the tests, but I can't seem to trigger the e_meta warning. This code should trigger it, right?
```R
load(system.file('testdata',
                 'little_pdata.RData',
                 package = 'pmartR'))
# add group and batch to fdata
fdata$Condition <- c(rep("Infection",6),rep("Mock",6))
fdata$Batch <- rep(seq(1:2),6)

# Create a pepData object with the reduced data set.
pdata <- as.pepData(e_data = edata,
                    f_data = fdata,
                    e_meta = emeta,
                    edata_cname = "Mass_Tag_ID",
                    fdata_cname = "SampleID",
                    emeta_cname = "Protein")

edr2_1 <- custom_filter(pdata,
                        e_data_remove = 6948849, e_meta_remove = "ALBU_HUMAN")
edr2_2 <- custom_filter(pdata,
                        e_data_remove = 6948849, e_meta_remove = "ALBU_HUMAN")

filtered_edr2_1 <- applyFilt(edr2_1, pdata)
filtered_edr2_2 <- applyFilt(edr2_2, pdata)
```
Debugging it it looks like maybe the values in e_meta_remove aren't actually being removed? I'll look into it further later today.

**Comment by evanglass** [comment]
Ah, nevermind. I found my problem, I was filtering pdata instead of filtered_edr2_1. Looks like it works as expected.
